apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tenant-manager
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.tenantManager.replicaCount }}
  selector:
    matchLabels:
      app: tenant-manager
  template:
    metadata:
      labels:
        app: tenant-manager
    spec:
      containers:
        - name: tenant-manager
          image: "{{ .Values.tenantManager.image.repository }}:{{ .Values.tenantManager.image.tag }}"
          ports:
            - containerPort: {{ .Values.tenantManager.port }}
          env:
            - name: PORT
              value: {{ .Values.tenantManager.port | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tenant-manager
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: tenant-manager
  ports:
    - port: {{ .Values.tenantManager.port }}
      targetPort: {{ .Values.tenantManager.port }}